SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE cliente;
TRUNCATE TABLE empresa;
TRUNCATE TABLE factura;
TRUNCATE TABLE particular;
TRUNCATE TABLE producto;
TRUNCATE TABLE proveedor;
TRUNCATE TABLE linea_factura;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente0', 'ES6863', False, 'NIF0');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente1', 'ES53377', False, 'NIF1');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente2', 'ES5000', False, 'NIF2');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente3', 'ES73704', False, 'NIF3');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente4', 'ES6802', False, 'NIF4');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente5', 'ES44199', True, 'NIF5');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente6', 'ES91971', False, 'NIF6');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente7', 'ES218', True, 'NIF7');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente8', 'ES11483', True, 'NIF8');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente9', 'ES49492', False, 'NIF9');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente10', 'ES41347', True, 'NIF10');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente11', 'ES13374', True, 'NIF11');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente12', 'ES12158', True, 'NIF12');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente13', 'ES16547', True, 'NIF13');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente14', 'ES2783', False, 'NIF14');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente15', 'ES56444', True, 'NIF15');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente16', 'ES34776', False, 'NIF16');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente17', 'ES4816', True, 'NIF17');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente18', 'ES45018', True, 'NIF18');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente19', 'ES63302', False, 'NIF19');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente20', 'ES79810', True, 'NIF20');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente21', 'ES74031', True, 'NIF21');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente22', 'ES41322', False, 'NIF22');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente23', 'ES84692', True, 'NIF23');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente24', 'ES89762', True, 'NIF24');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente25', 'ES87380', True, 'NIF25');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente26', 'ES63718', True, 'NIF26');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente27', 'ES54984', False, 'NIF27');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente28', 'ES4173', True, 'NIF28');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente29', 'ES84600', False, 'NIF29');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente30', 'ES10827', True, 'NIF30');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente31', 'ES86255', False, 'NIF31');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente32', 'ES43896', False, 'NIF32');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente33', 'ES51274', True, 'NIF33');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente34', 'ES94779', False, 'NIF34');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente35', 'ES75126', True, 'NIF35');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente36', 'ES2137', False, 'NIF36');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente37', 'ES11554', True, 'NIF37');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente38', 'ES47646', False, 'NIF38');
INSERT INTO cliente (nombre, cuenta_bancaria, activo, NIF) VALUES ('cliente39', 'ES46126', True, 'NIF39');
INSERT INTO empresa (direccion_social, id_cliente) VALUES ('direccion6647', 1);
INSERT INTO empresa (direccion_social, id_cliente) VALUES ('direccion8716', 2);
INSERT INTO empresa (direccion_social, id_cliente) VALUES ('direccion8208', 3);
INSERT INTO empresa (direccion_social, id_cliente) VALUES ('direccion978', 4);
INSERT INTO empresa (direccion_social, id_cliente) VALUES ('direccion4713', 5);
INSERT INTO empresa (direccion_social, id_cliente) VALUES ('direccion8106', 6);
INSERT INTO empresa (direccion_social, id_cliente) VALUES ('direccion3823', 7);
INSERT INTO empresa (direccion_social, id_cliente) VALUES ('direccion8915', 8);
INSERT INTO empresa (direccion_social, id_cliente) VALUES ('direccion7926', 9);
INSERT INTO empresa (direccion_social, id_cliente) VALUES ('direccion2909', 10);
INSERT INTO particular (id, fiel, id_cliente) VALUES (1, False, 11);
INSERT INTO particular (id, fiel, id_cliente) VALUES (2, True, 12);
INSERT INTO particular (id, fiel, id_cliente) VALUES (3, False, 13);
INSERT INTO particular (id, fiel, id_cliente) VALUES (4, False, 14);
INSERT INTO particular (id, fiel, id_cliente) VALUES (5, False, 15);
INSERT INTO particular (id, fiel, id_cliente) VALUES (6, False, 16);
INSERT INTO particular (id, fiel, id_cliente) VALUES (7, False, 17);
INSERT INTO particular (id, fiel, id_cliente) VALUES (8, True, 18);
INSERT INTO particular (id, fiel, id_cliente) VALUES (9, True, 19);
INSERT INTO particular (id, fiel, id_cliente) VALUES (10, True, 20);
INSERT INTO particular (id, fiel, id_cliente) VALUES (11, True, 21);
INSERT INTO particular (id, fiel, id_cliente) VALUES (12, False, 22);
INSERT INTO particular (id, fiel, id_cliente) VALUES (13, True, 23);
INSERT INTO particular (id, fiel, id_cliente) VALUES (14, True, 24);
INSERT INTO particular (id, fiel, id_cliente) VALUES (15, True, 25);
INSERT INTO particular (id, fiel, id_cliente) VALUES (16, False, 26);
INSERT INTO particular (id, fiel, id_cliente) VALUES (17, True, 27);
INSERT INTO particular (id, fiel, id_cliente) VALUES (18, True, 28);
INSERT INTO particular (id, fiel, id_cliente) VALUES (19, False, 29);
INSERT INTO particular (id, fiel, id_cliente) VALUES (20, True, 30);
INSERT INTO particular (id, fiel, id_cliente) VALUES (21, True, 31);
INSERT INTO particular (id, fiel, id_cliente) VALUES (22, False, 32);
INSERT INTO particular (id, fiel, id_cliente) VALUES (23, False, 33);
INSERT INTO particular (id, fiel, id_cliente) VALUES (24, True, 34);
INSERT INTO particular (id, fiel, id_cliente) VALUES (25, False, 35);
INSERT INTO particular (id, fiel, id_cliente) VALUES (26, True, 36);
INSERT INTO particular (id, fiel, id_cliente) VALUES (27, False, 37);
INSERT INTO particular (id, fiel, id_cliente) VALUES (28, False, 38);
INSERT INTO particular (id, fiel, id_cliente) VALUES (29, True, 39);
INSERT INTO particular (id, fiel, id_cliente) VALUES (30, False, 40);
INSERT INTO proveedor (nombre, activo) VALUES ('proveedor0', True);
INSERT INTO proveedor (nombre, activo) VALUES ('proveedor1', False);
INSERT INTO proveedor (nombre, activo) VALUES ('proveedor2', True);
INSERT INTO proveedor (nombre, activo) VALUES ('proveedor3', False);
INSERT INTO proveedor (nombre, activo) VALUES ('proveedor4', True);
INSERT INTO producto (nombre, precio, existencias, activo, id_proveedor) VALUES ('nombre0', 148.83, 937, True, 4);
INSERT INTO producto (nombre, precio, existencias, activo, id_proveedor) VALUES ('nombre1', 107.51, 2395, True, 3);
INSERT INTO producto (nombre, precio, existencias, activo, id_proveedor) VALUES ('nombre2', 155.23, 6378, False, 5);
INSERT INTO producto (nombre, precio, existencias, activo, id_proveedor) VALUES ('nombre3', 194.99, 8473, False, 2);
INSERT INTO producto (nombre, precio, existencias, activo, id_proveedor) VALUES ('nombre4', 160.46, 6329, False, 2);
INSERT INTO producto (nombre, precio, existencias, activo, id_proveedor) VALUES ('nombre5', 90.95, 338, False, 4);
INSERT INTO producto (nombre, precio, existencias, activo, id_proveedor) VALUES ('nombre6', 60.77, 463, False, 3);
INSERT INTO producto (nombre, precio, existencias, activo, id_proveedor) VALUES ('nombre7', 174.28, 8434, True, 3);
INSERT INTO producto (nombre, precio, existencias, activo, id_proveedor) VALUES ('nombre8', 100.03, 8937, True, 2);
INSERT INTO producto (nombre, precio, existencias, activo, id_proveedor) VALUES ('nombre9', 178.69, 5572, False, 5);
INSERT INTO factura (fecha, precio_total, id_cliente, activo) VALUES ('2003-4-29 10:16:25', 0, 3, True);
INSERT INTO factura (fecha, precio_total, id_cliente, activo) VALUES ('1998-4-17 6:48:57', 0, 2, False);
INSERT INTO factura (fecha, precio_total, id_cliente, activo) VALUES ('2014-4-3 19:20:5', 0, 22, True);
INSERT INTO factura (fecha, precio_total, id_cliente, activo) VALUES ('2000-9-5 15:31:46', 0, 26, True);
INSERT INTO factura (fecha, precio_total, id_cliente, activo) VALUES ('2004-12-27 18:55:31', 0, 22, False);
INSERT INTO factura (fecha, precio_total, id_cliente, activo) VALUES ('2003-9-30 4:39:40', 0, 1, True);
INSERT INTO factura (fecha, precio_total, id_cliente, activo) VALUES ('2015-10-16 10:44:37', 0, 8, True);
INSERT INTO factura (fecha, precio_total, id_cliente, activo) VALUES ('2007-8-12 21:54:26', 0, 21, False);
INSERT INTO factura (fecha, precio_total, id_cliente, activo) VALUES ('2020-8-11 6:52:11', 0, 25, True);
INSERT INTO factura (fecha, precio_total, id_cliente, activo) VALUES ('1997-7-13 16:16:53', 0, 12, True);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (6, 364.62, 7, 2);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (2, 320.92, 5, 5);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (10, 1000.3, 9, 6);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (7, 1041.81, 1, 1);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (7, 1250.83, 10, 5);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (8, 860.08, 2, 10);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (4, 363.8, 6, 8);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (8, 1283.68, 5, 10);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (6, 1072.14, 10, 4);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (9, 1568.52, 8, 10);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (6, 962.76, 5, 1);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (2, 310.46, 3, 1);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (8, 486.16, 7, 3);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (9, 1568.52, 8, 1);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (9, 1568.52, 8, 3);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (6, 545.7, 6, 4);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (1, 178.69, 10, 8);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (10, 1000.3, 9, 5);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (1, 178.69, 10, 6);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (4, 243.08, 7, 2);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (5, 802.3, 5, 3);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (6, 364.62, 7, 7);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (10, 1488.3, 1, 1);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (3, 522.84, 8, 4);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (5, 744.15, 1, 9);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (9, 1397.07, 3, 4);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (8, 1283.68, 5, 8);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (5, 974.95, 4, 9);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (2, 215.02, 2, 8);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (9, 1608.21, 10, 9);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (4, 641.84, 5, 9);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (7, 752.57, 2, 7);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (2, 348.56, 8, 1);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (7, 1250.83, 10, 7);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (6, 600.18, 9, 3);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (3, 522.84, 8, 4);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (4, 779.96, 4, 1);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (4, 779.96, 4, 2);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (1, 60.77, 7, 1);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (6, 364.62, 7, 9);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (1, 148.83, 1, 4);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (5, 303.85, 7, 3);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (2, 320.92, 5, 5);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (4, 363.8, 6, 9);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (6, 892.98, 1, 3);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (4, 697.12, 8, 7);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (9, 1754.91, 4, 7);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (9, 546.93, 7, 4);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (2, 121.54, 7, 8);
INSERT INTO linea_factura (cantidad, precio_venta, id_producto, id_factura) VALUES (5, 744.15, 1, 3);
UPDATE factura SET precio_total=46567.56 WHERE id=1;
UPDATE factura SET precio_total=6279.88 WHERE id=2;
UPDATE factura SET precio_total=36216.42 WHERE id=3;
UPDATE factura SET precio_total=30488.91 WHERE id=4;
UPDATE factura SET precio_total=20042.49 WHERE id=5;
UPDATE factura SET precio_total=10181.69 WHERE id=6;
UPDATE factura SET precio_total=34794.19 WHERE id=7;
UPDATE factura SET precio_total=12576.45 WHERE id=8;
UPDATE factura SET precio_total=29279.67 WHERE id=9;
UPDATE factura SET precio_total=31266.76 WHERE id=10;
