SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE cliente;
TRUNCATE TABLE empresa;
TRUNCATE TABLE factura;
TRUNCATE TABLE particular;
TRUNCATE TABLE producto;
TRUNCATE TABLE proveedor;
TRUNCATE TABLE venta;
SET FOREIGN_KEY_CHECKS = 1;